<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHxuhruS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHxuhruS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHxuhruS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHxuhruS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHxuhruS\App_KernelDevDebugContainer([
    'container.build_hash' => 'HxuhruS',
    'container.build_id' => '77d72687',
    'container.build_time' => 1590732604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHxuhruS');
